### ISSUE TITLE
pip install e2me不成功

### ISSUE THREAD

**Issue by YuDi0-0** [luzhixing12345/e2me#1]
(tf_26) C:\Users\YUDI>pip install e2me
ERROR: Could not find a version that satisfies the requirement e2me (from versions: none)
ERROR: No matching distribution found for e2me

**Comment by luzhixing12345** [comment]
您好，看起来是 pip 安装的时候失败了，我没有成功复现您的问题

您可以使用如下命令尝试

```bash
pip install -U e2me --index-url https://pypi.tuna.tsinghua.edu.cn/simple
```

**Comment by YuDi0-0** [comment]
> 您好，看起来是 pip 安装的时候失败了，我没有成功复现您的问题
> 
> 您可以使用如下命令尝试
> 
> ```shell
> pip install -U e2me --index-url https://pypi.tuna.tsinghua.edu.cn/simple
> ```

啊，找到原因了哥，我用的是py3.6，这个包支持范围是3.7-4.0。哭了，未来会支持py3.6嘛QAQ

**Comment by YuDi0-0** [comment]
我重新建立了cp38的环境，现在可以在python中正常发送邮件了。有一个小疑问，似乎我必须将e2me.toml文件放在需要执行的.py同目录下，这样未来的任何项目都需要复制一个文件在本目录下么？请问有什么方法可以让他直接从环境中、或者固定目录下获取e2me.toml文件么？

**Comment by luzhixing12345** [comment]
> > 您好，看起来是 pip 安装的时候失败了，我没有成功复现您的问题
> > 您可以使用如下命令尝试
> > ```shell
> > pip install -U e2me --index-url https://pypi.tuna.tsinghua.edu.cn/simple
> > ```
> 
> 啊，找到原因了哥，我用的是py3.6，这个包支持范围是3.7-4.0。哭了，未来会支持py3.6嘛QAQ

我没有想到还有人在用这么早期的python版本了，已经支持了

> 我重新建立了cp38的环境，现在可以在python中正常发送邮件了。有一个小疑问，似乎我必须将e2me.toml文件放在需要执行的.py同目录下，这样未来的任何项目都需要复制一个文件在本目录下么？请问有什么方法可以让他直接从环境中、或者固定目录下获取e2me.toml文件么？

更新了一下，如果没有当前目录的 e2me.toml 默认会在全局目录中搜索，你可以编辑一次然后使用 e2me -s 覆盖默认，如果没有本地 e2me.toml 就会使用全局的配置，这样就可以直接在任何位置使用 e2me run 了

可以安装最新版试一下

```bash
pip install -U e2me
```
