### ISSUE TITLE
No module named chardet

### ISSUE THREAD

**Issue by RRZ233** [luzhixing12345/e2me#2]
我在新装的环境中使用e2me发生了以下报错（python3.13.0 64-bit），这在我的3.12中是从来没发生的（也可能是我下的乱八七糟的包囊括了），解决方法很简单，就是使用`pip install chardet`。我发这个issue是因为想知道这是新版python的问题吗？

**Comment by luzhixing12345** [comment]
我的问题，忘记添加这个依赖了，我以为是标准库里面的，最新版修复了
