### ISSUE TITLE
【tips】有一个小想法

### ISSUE THREAD

**Issue by YuDi0-0** [luzhixing12345/e2me#3]
我现在是在python代码的末尾运行e2me.run()以实现代码运行完之后给我发邮件，但如果代码中途报错了他就不会发邮件了。
所以有一个小想法，可不可以在代码初始运行一个命令，检测代码运行的状态，如果运行完了或者报错了则发邮件呢？
此外，可以在发邮件时带上运行程序的名称么？（同时跑多个程序的时候不知道是哪个运行完了）

**Comment by luzhixing12345** [comment]
> 我现在是在python代码的末尾运行e2me.run()以实现代码运行完之后给我发邮件，但如果代码中途报错了他就不会发邮件了。 所以有一个小想法，可不可以在代码初始运行一个命令，检测代码运行的状态，如果运行完了或者报错了则发邮件呢？ 

我理解如果代码中途可能报错最好的解决办法是用 try except 包起来，如下所示

```python
import e2me

if __name__ == "__main__":
    
    try:
        print(x)
        e2me.run()
    except Exception as e:
        print(e)
        e2me.run("运行失败")
```

> 此外，可以在发邮件时带上运行程序的名称么？（同时跑多个程序的时候不知道是哪个运行完了）

这个提议很好！为 run 添加了一个参数可以修改默认 subject 内容，以及命令行中的 --subject 

```python
def run(subject_str: str = "", config_path: str = "e2me.toml")
```

您可以使用最新版的 e2me (0.0.9)使用此功能

```bash
pip install -U e2me
```

**Comment by YuDi0-0** [comment]
一个新的想法，请问能够实现嘛？
由于用163邮箱给自己发邮件在手机端无法聚合聊天内容，导致每次都出现一个新对话，请问是否可以设置为将邮件发送给另外一个邮箱号，这样手机端就可以正常聚合聊天内容了

![Image](https://github.com/user-attachments/assets/ff8736e6-f0b6-47b8-b69a-c2a069f6d258)

**Comment by luzhixing12345** [comment]
我没理解这个需求的含义。邮件和聊天软件的形式不一样，本身的沟通形式就是一封一封，不管发给别人，发给自己还是回复邮件都是创建一个独立的邮件信息窗口，不存在聚合在一个窗口的情况吧

而且发给别人的话自己也并不会收到新邮件的提醒啊，是要自己登录两个邮箱A发给B么？没太理解您的意思

**Comment by YuDi0-0** [comment]
对的，就是想用邮箱A发给B（目前是A发给A），因为网易邮箱大师上是可以将同一个人的邮件聚合成类似聊天形式的，但是如果是本邮箱号发给自己的就聚合不起来
